/* Generated by Yosys 0.9+4288 (git sha1 b2e97174, x86_64-conda_cos6-linux-gnu-gcc 1.24.0.133_b0863d8_dirty -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1630451134687/work=/usr/local/src/conda/yosys-0.9_5586_gb2e97174 -fdebug-prefix-map=/home/carlos/miniconda3/envs/fpga=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

/* top =  1  */
/* src = "MappedSPIFlash_V3.v:3.1-148.10" */
module MappedSPIFlash(clk, reset, rstrb, word_address, rdata, rbusy, CLK, CS_N, MOSI, MISO);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  /* src = "MappedSPIFlash_V3.v:50.11-50.33" */
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:0.0-0.0|MappedSPIFlash_V3.v:76.5-132.12|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:575.21-575.22" */
  wire [5:0] _057_;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:0.0-0.0|MappedSPIFlash_V3.v:76.5-132.12|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:575.21-575.22" */
  wire [31:0] _058_;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:0.0-0.0|MappedSPIFlash_V3.v:76.5-132.12|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:575.21-575.22" */
  wire [5:0] _059_;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:0.0-0.0|MappedSPIFlash_V3.v:76.5-132.12|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:575.21-575.22" */
  wire _060_;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:0.0-0.0|MappedSPIFlash_V3.v:76.5-132.12|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:575.21-575.22" */
  wire _061_;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:270.23-270.24" */
  wire [31:0] _062_;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:270.26-270.27" */
  /* unused_bits = "6" */
  wire [31:0] _063_;
  /* src = "MappedSPIFlash_V3.v:13.23-13.26" */
  output CLK;
  reg CLK;
  /* src = "MappedSPIFlash_V3.v:14.24-14.28" */
  output CS_N;
  reg CS_N;
  /* src = "MappedSPIFlash_V3.v:16.24-16.28" */
  input MISO;
  /* src = "MappedSPIFlash_V3.v:15.24-15.28" */
  output MOSI;
  /* src = "MappedSPIFlash_V3.v:4.24-4.27" */
  input clk;
  /* src = "MappedSPIFlash_V3.v:31.6-31.13" */
  reg clk_div;
  /* src = "MappedSPIFlash_V3.v:36.15-36.23" */
  reg [31:0] cmd_addr;
  /* src = "MappedSPIFlash_V3.v:40.15-40.26" */
  reg [5:0] div_counter;
  /* src = "MappedSPIFlash_V3.v:10.23-10.28" */
  output rbusy;
  reg rbusy;
  /* src = "MappedSPIFlash_V3.v:37.15-37.27" */
  reg [5:0] rcv_bitcount;
  /* src = "MappedSPIFlash_V3.v:38.15-38.23" */
  reg [31:0] rcv_data;
  /* src = "MappedSPIFlash_V3.v:9.24-9.29" */
  output [31:0] rdata;
  /* src = "MappedSPIFlash_V3.v:5.24-5.29" */
  input reset;
  /* src = "MappedSPIFlash_V3.v:6.24-6.29" */
  input rstrb;
  /* src = "MappedSPIFlash_V3.v:35.15-35.27" */
  reg [5:0] snd_bitcount;
  /* onehot = 32'd1 */
  reg [3:0] state;
  /* src = "MappedSPIFlash_V3.v:7.24-7.36" */
  input [19:0] word_address;
  sky130_fd_sc_hd__clkinv_1 _064_ (
    .A(div_counter[0]),
    .Y(_062_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _065_ (
    .A(reset),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a2111oi_0 _066_ (
    .A1(div_counter[1]),
    .A2(div_counter[2]),
    .B1(div_counter[4]),
    .C1(div_counter[5]),
    .D1(div_counter[3]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _067_ (
    .A(_013_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _068_ (
    .A(div_counter[0]),
    .B(div_counter[1]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o21ai_0 _069_ (
    .A1(div_counter[2]),
    .A2(_014_),
    .B1(_013_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _070_ (
    .A(state[2]),
    .SLEEP(rstrb),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _071_ (
    .A(state[2]),
    .B(state[0]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _072_ (
    .A(rstrb),
    .B(state[2]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _073_ (
    .A(_017_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _074_ (
    .A(_015_),
    .B(_016_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _075_ (
    .A(snd_bitcount[0]),
    .SLEEP(snd_bitcount[1]),
    .X(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _076_ (
    .A(snd_bitcount[3]),
    .B(snd_bitcount[4]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor4_1 _077_ (
    .A(snd_bitcount[2]),
    .B(snd_bitcount[3]),
    .C(snd_bitcount[4]),
    .D(snd_bitcount[5]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _078_ (
    .A(clk_div),
    .B(state[1]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand4_1 _079_ (
    .A(clk_div),
    .B(state[1]),
    .C(_018_),
    .D(_020_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _080_ (
    .A(state[1]),
    .SLEEP(clk_div),
    .X(_023_)
  );
  sky130_fd_sc_hd__nand2b_1 _081_ (
    .A_N(clk_div),
    .B(state[1]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _082_ (
    .A(state[2]),
    .B(state[1]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor3_1 _083_ (
    .A(state[2]),
    .B(state[1]),
    .C(state[0]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor3_1 _084_ (
    .A(_015_),
    .B(_023_),
    .C(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__and3_1 _085_ (
    .A(reset),
    .B(_022_),
    .C(_027_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _086_ (
    .A(_015_),
    .B(_025_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__and3_1 _087_ (
    .A(_022_),
    .B(_024_),
    .C(_028_),
    .X(_007_)
  );
  sky130_fd_sc_hd__or3_1 _088_ (
    .A(rcv_bitcount[0]),
    .B(rcv_bitcount[2]),
    .C(rcv_bitcount[1]),
    .X(_029_)
  );
  sky130_fd_sc_hd__or4_1 _089_ (
    .A(rcv_bitcount[0]),
    .B(rcv_bitcount[3]),
    .C(rcv_bitcount[2]),
    .D(rcv_bitcount[1]),
    .X(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _090_ (
    .A(clk_div),
    .B(state[3]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor4_1 _091_ (
    .A(rcv_bitcount[4]),
    .B(rcv_bitcount[5]),
    .C(_030_),
    .D(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21boi_0 _092_ (
    .A1(_018_),
    .A2(_020_),
    .B1_N(state[1]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a21oi_1 _093_ (
    .A1(_018_),
    .A2(_020_),
    .B1(_021_),
    .Y(_058_[0])
  );
  sky130_fd_sc_hd__nor3_1 _094_ (
    .A(state[1]),
    .B(state[3]),
    .C(state[0]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2b_1 _095_ (
    .A_N(clk_div),
    .B(state[3]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand3_1 _096_ (
    .A(reset),
    .B(_024_),
    .C(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor4_1 _097_ (
    .A(_032_),
    .B(_058_[0]),
    .C(_034_),
    .D(_036_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o311ai_0 _098_ (
    .A1(rcv_bitcount[4]),
    .A2(rcv_bitcount[5]),
    .A3(_030_),
    .B1(state[3]),
    .C1(clk_div),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _099_ (
    .A(_037_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a31oi_1 _100_ (
    .A1(_022_),
    .A2(_035_),
    .A3(_037_),
    .B1(_012_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _101_ (
    .A(state[0]),
    .B(_015_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _102_ (
    .A(_012_),
    .B(_038_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__o31a_1 _103_ (
    .A1(_061_),
    .A2(_023_),
    .A3(_033_),
    .B1(reset),
    .X(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _104_ (
    .A(reset),
    .B(_013_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _105_ (
    .A(_012_),
    .SLEEP(_032_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _106_ (
    .A(rcv_bitcount[0]),
    .B(_037_),
    .Y(_057_[0])
  );
  sky130_fd_sc_hd__xor2_1 _107_ (
    .A(rcv_bitcount[0]),
    .B(rcv_bitcount[1]),
    .X(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _108_ (
    .A(_037_),
    .B(_039_),
    .Y(_057_[1])
  );
  sky130_fd_sc_hd__o21ai_0 _109_ (
    .A1(rcv_bitcount[0]),
    .A2(rcv_bitcount[1]),
    .B1(rcv_bitcount[2]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _110_ (
    .A1(_029_),
    .A2(_040_),
    .B1(_037_),
    .Y(_057_[2])
  );
  sky130_fd_sc_hd__nand2_1 _111_ (
    .A(rcv_bitcount[3]),
    .B(_029_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a21oi_1 _112_ (
    .A1(_030_),
    .A2(_041_),
    .B1(_037_),
    .Y(_057_[3])
  );
  sky130_fd_sc_hd__xor2_1 _113_ (
    .A(rcv_bitcount[4]),
    .B(_030_),
    .X(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _114_ (
    .A(_037_),
    .B(_042_),
    .Y(_057_[4])
  );
  sky130_fd_sc_hd__o2111ai_1 _115_ (
    .A1(rcv_bitcount[4]),
    .A2(_030_),
    .B1(rcv_bitcount[5]),
    .C1(clk_div),
    .D1(state[3]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(_022_),
    .B(_043_),
    .Y(_057_[5])
  );
  sky130_fd_sc_hd__and2_0 _117_ (
    .A(cmd_addr[0]),
    .B(_058_[0]),
    .X(_058_[1])
  );
  sky130_fd_sc_hd__a22o_1 _118_ (
    .A1(word_address[0]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[1]),
    .X(_058_[2])
  );
  sky130_fd_sc_hd__a22o_1 _119_ (
    .A1(word_address[1]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[2]),
    .X(_058_[3])
  );
  sky130_fd_sc_hd__a22o_1 _120_ (
    .A1(word_address[2]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[3]),
    .X(_058_[4])
  );
  sky130_fd_sc_hd__a22o_1 _121_ (
    .A1(word_address[3]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[4]),
    .X(_058_[5])
  );
  sky130_fd_sc_hd__a22o_1 _122_ (
    .A1(word_address[4]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[5]),
    .X(_058_[6])
  );
  sky130_fd_sc_hd__a22o_1 _123_ (
    .A1(word_address[5]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[6]),
    .X(_058_[7])
  );
  sky130_fd_sc_hd__a22o_1 _124_ (
    .A1(word_address[6]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[7]),
    .X(_058_[8])
  );
  sky130_fd_sc_hd__a22o_1 _125_ (
    .A1(word_address[7]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[8]),
    .X(_058_[9])
  );
  sky130_fd_sc_hd__a22o_1 _126_ (
    .A1(word_address[8]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[9]),
    .X(_058_[10])
  );
  sky130_fd_sc_hd__a22o_1 _127_ (
    .A1(word_address[9]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[10]),
    .X(_058_[11])
  );
  sky130_fd_sc_hd__a22o_1 _128_ (
    .A1(word_address[10]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[11]),
    .X(_058_[12])
  );
  sky130_fd_sc_hd__a22o_1 _129_ (
    .A1(word_address[11]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[12]),
    .X(_058_[13])
  );
  sky130_fd_sc_hd__a22o_1 _130_ (
    .A1(word_address[12]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[13]),
    .X(_058_[14])
  );
  sky130_fd_sc_hd__a22o_1 _131_ (
    .A1(word_address[13]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[14]),
    .X(_058_[15])
  );
  sky130_fd_sc_hd__a22o_1 _132_ (
    .A1(word_address[14]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[15]),
    .X(_058_[16])
  );
  sky130_fd_sc_hd__a22o_1 _133_ (
    .A1(word_address[15]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[16]),
    .X(_058_[17])
  );
  sky130_fd_sc_hd__a22o_1 _134_ (
    .A1(word_address[16]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[17]),
    .X(_058_[18])
  );
  sky130_fd_sc_hd__a22o_1 _135_ (
    .A1(word_address[17]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[18]),
    .X(_058_[19])
  );
  sky130_fd_sc_hd__a22o_1 _136_ (
    .A1(word_address[18]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[19]),
    .X(_058_[20])
  );
  sky130_fd_sc_hd__a22o_1 _137_ (
    .A1(word_address[19]),
    .A2(_061_),
    .B1(_058_[0]),
    .B2(cmd_addr[20]),
    .X(_058_[21])
  );
  sky130_fd_sc_hd__and2_0 _138_ (
    .A(cmd_addr[21]),
    .B(_058_[0]),
    .X(_058_[22])
  );
  sky130_fd_sc_hd__and2_0 _139_ (
    .A(cmd_addr[22]),
    .B(_058_[0]),
    .X(_058_[23])
  );
  sky130_fd_sc_hd__a21o_1 _140_ (
    .A1(cmd_addr[23]),
    .A2(_058_[0]),
    .B1(_061_),
    .X(_058_[24])
  );
  sky130_fd_sc_hd__a21o_1 _141_ (
    .A1(cmd_addr[24]),
    .A2(_058_[0]),
    .B1(_061_),
    .X(_058_[25])
  );
  sky130_fd_sc_hd__and2_0 _142_ (
    .A(cmd_addr[25]),
    .B(_058_[0]),
    .X(_058_[26])
  );
  sky130_fd_sc_hd__and2_0 _143_ (
    .A(cmd_addr[26]),
    .B(_058_[0]),
    .X(_058_[27])
  );
  sky130_fd_sc_hd__and2_0 _144_ (
    .A(cmd_addr[27]),
    .B(_058_[0]),
    .X(_058_[28])
  );
  sky130_fd_sc_hd__and2_0 _145_ (
    .A(cmd_addr[28]),
    .B(_058_[0]),
    .X(_058_[29])
  );
  sky130_fd_sc_hd__and2_0 _146_ (
    .A(cmd_addr[29]),
    .B(_058_[0]),
    .X(_058_[30])
  );
  sky130_fd_sc_hd__and2_0 _147_ (
    .A(cmd_addr[30]),
    .B(_058_[0]),
    .X(_058_[31])
  );
  sky130_fd_sc_hd__nor2_1 _148_ (
    .A(snd_bitcount[0]),
    .B(_021_),
    .Y(_059_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _149_ (
    .A(snd_bitcount[1]),
    .SLEEP(snd_bitcount[0]),
    .X(_044_)
  );
  sky130_fd_sc_hd__nor3_1 _150_ (
    .A(_018_),
    .B(_021_),
    .C(_044_),
    .Y(_059_[1])
  );
  sky130_fd_sc_hd__o21ai_0 _151_ (
    .A1(snd_bitcount[0]),
    .A2(snd_bitcount[1]),
    .B1(snd_bitcount[2]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _152_ (
    .A(snd_bitcount[0]),
    .B(snd_bitcount[1]),
    .C(snd_bitcount[2]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _153_ (
    .A(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a21oi_1 _154_ (
    .A1(_045_),
    .A2(_047_),
    .B1(_021_),
    .Y(_059_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _155_ (
    .A(snd_bitcount[3]),
    .B(_046_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _156_ (
    .A(_021_),
    .B(_048_),
    .Y(_059_[3])
  );
  sky130_fd_sc_hd__o41ai_1 _157_ (
    .A1(snd_bitcount[0]),
    .A2(snd_bitcount[1]),
    .A3(snd_bitcount[2]),
    .A4(snd_bitcount[3]),
    .B1(snd_bitcount[4]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _158_ (
    .A(_019_),
    .B(_046_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _159_ (
    .A1(_049_),
    .A2(_050_),
    .B1(_021_),
    .Y(_059_[4])
  );
  sky130_fd_sc_hd__and3_1 _160_ (
    .A(snd_bitcount[5]),
    .B(_019_),
    .C(_046_),
    .X(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _161_ (
    .A1(_019_),
    .A2(_046_),
    .B1(snd_bitcount[5]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o31ai_1 _162_ (
    .A1(_021_),
    .A2(_051_),
    .A3(_052_),
    .B1(_017_),
    .Y(_059_[5])
  );
  sky130_fd_sc_hd__nor3b_1 _163_ (
    .A(CS_N),
    .B(CLK),
    .C_N(_004_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__xor2_1 _164_ (
    .A(div_counter[0]),
    .B(div_counter[1]),
    .X(_063_[1])
  );
  sky130_fd_sc_hd__xnor2_1 _165_ (
    .A(div_counter[2]),
    .B(_014_),
    .Y(_063_[2])
  );
  sky130_fd_sc_hd__nand4_1 _166_ (
    .A(div_counter[3]),
    .B(div_counter[0]),
    .C(div_counter[1]),
    .D(div_counter[2]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a31oi_1 _167_ (
    .A1(div_counter[0]),
    .A2(div_counter[1]),
    .A3(div_counter[2]),
    .B1(div_counter[3]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _168_ (
    .A(_053_),
    .SLEEP(_054_),
    .X(_063_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _169_ (
    .A(div_counter[4]),
    .SLEEP(_053_),
    .X(_055_)
  );
  sky130_fd_sc_hd__xnor2_1 _170_ (
    .A(div_counter[4]),
    .B(_053_),
    .Y(_063_[4])
  );
  sky130_fd_sc_hd__xor2_1 _171_ (
    .A(div_counter[5]),
    .B(_055_),
    .X(_063_[5])
  );
  sky130_fd_sc_hd__buf_1 _172_ (
    .A(state[0]),
    .X(_060_)
  );
  always @(negedge clk)
    state[0] <= _000_;
  always @(negedge clk)
    state[1] <= _001_;
  always @(negedge clk)
    state[2] <= _002_;
  always @(negedge clk)
    state[3] <= _003_;
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_008_) snd_bitcount[0] <= _059_[0];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_008_) snd_bitcount[1] <= _059_[1];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_008_) snd_bitcount[2] <= _059_[2];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_008_) snd_bitcount[3] <= _059_[3];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_008_) snd_bitcount[4] <= _059_[4];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_008_) snd_bitcount[5] <= _059_[5];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_006_) rcv_bitcount[0] <= _057_[0];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_006_) rcv_bitcount[1] <= _057_[1];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_006_) rcv_bitcount[2] <= _057_[2];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_006_) rcv_bitcount[3] <= _057_[3];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_006_) rcv_bitcount[4] <= _057_[4];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (_006_) rcv_bitcount[5] <= _057_[5];
  /* src = "MappedSPIFlash_V3.v:43.1-64.4" */
  always @(negedge clk)
    if (_010_) div_counter[0] <= 1'h0;
    else div_counter[0] <= _062_[0];
  /* src = "MappedSPIFlash_V3.v:43.1-64.4" */
  always @(negedge clk)
    if (_010_) div_counter[1] <= 1'h0;
    else div_counter[1] <= _063_[1];
  /* src = "MappedSPIFlash_V3.v:43.1-64.4" */
  always @(negedge clk)
    if (_010_) div_counter[2] <= 1'h0;
    else div_counter[2] <= _063_[2];
  /* src = "MappedSPIFlash_V3.v:43.1-64.4" */
  always @(negedge clk)
    if (_010_) div_counter[3] <= 1'h0;
    else div_counter[3] <= _063_[3];
  /* src = "MappedSPIFlash_V3.v:43.1-64.4" */
  always @(negedge clk)
    if (_010_) div_counter[4] <= 1'h0;
    else div_counter[4] <= _063_[4];
  /* src = "MappedSPIFlash_V3.v:43.1-64.4" */
  always @(negedge clk)
    if (_010_) div_counter[5] <= 1'h0;
    else div_counter[5] <= _063_[5];
  /* src = "MappedSPIFlash_V3.v:43.1-64.4" */
  always @(negedge clk)
    if (!reset) clk_div <= 1'h0;
    else clk_div <= _011_;
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rbusy <= 1'h0;
    else if (_009_) rbusy <= _061_;
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) CS_N <= 1'h1;
    else if (_009_) CS_N <= _060_;
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[0] <= 1'h0;
    else if (_007_) cmd_addr[0] <= _058_[0];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[1] <= 1'h0;
    else if (_007_) cmd_addr[1] <= _058_[1];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[2] <= 1'h0;
    else if (_007_) cmd_addr[2] <= _058_[2];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[3] <= 1'h0;
    else if (_007_) cmd_addr[3] <= _058_[3];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[4] <= 1'h0;
    else if (_007_) cmd_addr[4] <= _058_[4];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[5] <= 1'h0;
    else if (_007_) cmd_addr[5] <= _058_[5];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[6] <= 1'h0;
    else if (_007_) cmd_addr[6] <= _058_[6];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[7] <= 1'h0;
    else if (_007_) cmd_addr[7] <= _058_[7];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[8] <= 1'h0;
    else if (_007_) cmd_addr[8] <= _058_[8];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[9] <= 1'h0;
    else if (_007_) cmd_addr[9] <= _058_[9];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[10] <= 1'h0;
    else if (_007_) cmd_addr[10] <= _058_[10];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[11] <= 1'h0;
    else if (_007_) cmd_addr[11] <= _058_[11];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[12] <= 1'h0;
    else if (_007_) cmd_addr[12] <= _058_[12];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[13] <= 1'h0;
    else if (_007_) cmd_addr[13] <= _058_[13];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[14] <= 1'h0;
    else if (_007_) cmd_addr[14] <= _058_[14];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[15] <= 1'h0;
    else if (_007_) cmd_addr[15] <= _058_[15];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[16] <= 1'h0;
    else if (_007_) cmd_addr[16] <= _058_[16];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[17] <= 1'h0;
    else if (_007_) cmd_addr[17] <= _058_[17];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[18] <= 1'h0;
    else if (_007_) cmd_addr[18] <= _058_[18];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[19] <= 1'h0;
    else if (_007_) cmd_addr[19] <= _058_[19];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[20] <= 1'h0;
    else if (_007_) cmd_addr[20] <= _058_[20];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[21] <= 1'h0;
    else if (_007_) cmd_addr[21] <= _058_[21];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[22] <= 1'h0;
    else if (_007_) cmd_addr[22] <= _058_[22];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[23] <= 1'h0;
    else if (_007_) cmd_addr[23] <= _058_[23];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[24] <= 1'h0;
    else if (_007_) cmd_addr[24] <= _058_[24];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[25] <= 1'h0;
    else if (_007_) cmd_addr[25] <= _058_[25];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[26] <= 1'h0;
    else if (_007_) cmd_addr[26] <= _058_[26];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[27] <= 1'h0;
    else if (_007_) cmd_addr[27] <= _058_[27];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[28] <= 1'h0;
    else if (_007_) cmd_addr[28] <= _058_[28];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[29] <= 1'h0;
    else if (_007_) cmd_addr[29] <= _058_[29];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[30] <= 1'h0;
    else if (_007_) cmd_addr[30] <= _058_[30];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) cmd_addr[31] <= 1'h0;
    else if (_007_) cmd_addr[31] <= _058_[31];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[0] <= 1'h0;
    else if (_005_) rcv_data[0] <= MISO;
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[1] <= 1'h0;
    else if (_005_) rcv_data[1] <= rcv_data[0];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[2] <= 1'h0;
    else if (_005_) rcv_data[2] <= rcv_data[1];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[3] <= 1'h0;
    else if (_005_) rcv_data[3] <= rcv_data[2];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[4] <= 1'h0;
    else if (_005_) rcv_data[4] <= rcv_data[3];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[5] <= 1'h0;
    else if (_005_) rcv_data[5] <= rcv_data[4];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[6] <= 1'h0;
    else if (_005_) rcv_data[6] <= rcv_data[5];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[7] <= 1'h0;
    else if (_005_) rcv_data[7] <= rcv_data[6];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[8] <= 1'h0;
    else if (_005_) rcv_data[8] <= rcv_data[7];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[9] <= 1'h0;
    else if (_005_) rcv_data[9] <= rcv_data[8];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[10] <= 1'h0;
    else if (_005_) rcv_data[10] <= rcv_data[9];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[11] <= 1'h0;
    else if (_005_) rcv_data[11] <= rcv_data[10];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[12] <= 1'h0;
    else if (_005_) rcv_data[12] <= rcv_data[11];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[13] <= 1'h0;
    else if (_005_) rcv_data[13] <= rcv_data[12];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[14] <= 1'h0;
    else if (_005_) rcv_data[14] <= rcv_data[13];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[15] <= 1'h0;
    else if (_005_) rcv_data[15] <= rcv_data[14];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[16] <= 1'h0;
    else if (_005_) rcv_data[16] <= rcv_data[15];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[17] <= 1'h0;
    else if (_005_) rcv_data[17] <= rcv_data[16];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[18] <= 1'h0;
    else if (_005_) rcv_data[18] <= rcv_data[17];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[19] <= 1'h0;
    else if (_005_) rcv_data[19] <= rcv_data[18];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[20] <= 1'h0;
    else if (_005_) rcv_data[20] <= rcv_data[19];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[21] <= 1'h0;
    else if (_005_) rcv_data[21] <= rcv_data[20];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[22] <= 1'h0;
    else if (_005_) rcv_data[22] <= rcv_data[21];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[23] <= 1'h0;
    else if (_005_) rcv_data[23] <= rcv_data[22];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[24] <= 1'h0;
    else if (_005_) rcv_data[24] <= rcv_data[23];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[25] <= 1'h0;
    else if (_005_) rcv_data[25] <= rcv_data[24];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[26] <= 1'h0;
    else if (_005_) rcv_data[26] <= rcv_data[25];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[27] <= 1'h0;
    else if (_005_) rcv_data[27] <= rcv_data[26];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[28] <= 1'h0;
    else if (_005_) rcv_data[28] <= rcv_data[27];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[29] <= 1'h0;
    else if (_005_) rcv_data[29] <= rcv_data[28];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[30] <= 1'h0;
    else if (_005_) rcv_data[30] <= rcv_data[29];
  /* src = "MappedSPIFlash_V3.v:67.1-134.4" */
  always @(negedge clk)
    if (!reset) rcv_data[31] <= 1'h0;
    else if (_005_) rcv_data[31] <= rcv_data[30];
  /* src = "MappedSPIFlash_V3.v:43.1-64.4" */
  always @(negedge clk)
    if (!reset) CLK <= 1'h0;
    else if (_004_) CLK <= _056_;
  assign _062_[31:1] = { 26'h0000000, div_counter[5:1] };
  assign { _063_[31:7], _063_[0] } = { 25'h0000000, _062_[0] };
  assign MOSI = cmd_addr[31];
  assign rdata = { rcv_data[7:0], rcv_data[15:8], rcv_data[23:16], rcv_data[31:24] };
endmodule
