/* Generated by Yosys 0.59+62 (git sha1 9aa2dde7e, g++ 14.2.0-19ubuntu2 -fPIC -O3) */

/* hdlname = "mult_32" */
/* top =  1  */
/* src = "mult_32.v:1.1-27.10" */
module mult_32(clk, rst, init, A, B, pp, done);
  /* src = "mult_32.v:4.9-4.12" */
  input clk;
  wire clk;
  /* src = "mult_32.v:3.9-3.12" */
  input rst;
  wire rst;
  /* src = "mult_32.v:5.9-5.13" */
  input init;
  wire init;
  /* src = "mult_32.v:6.16-6.17" */
  input [15:0] A;
  wire [15:0] A;
  /* src = "mult_32.v:7.16-7.17" */
  input [15:0] B;
  wire [15:0] B;
  /* src = "mult_32.v:8.17-8.19" */
  output [31:0] pp;
  wire [31:0] pp;
  /* src = "mult_32.v:9.10-9.14" */
  output done;
  wire done;
  /* hdlname = "acc0 A" */
  /* src = "acc.v:3.16-3.17" */
  wire [31:0] \acc0.A ;
  /* hdlname = "acc0 clk" */
  /* src = "acc.v:2.9-2.12" */
  wire \acc0.clk ;
  /* hdlname = "acc0 pp" */
  /* src = "acc.v:6.21-6.23" */
  wire [31:0] \acc0.pp ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_10_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_11_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_12_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_13_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_14_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_15_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_1_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_2_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \acc0.pp_CCU2C_B0_3_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_4_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_5_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_6_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_7_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_8_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_9_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/usr/local/bin/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.pp_CCU2C_B0_COUT ;
  /* force_downto = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:34.26-34.27" */
  wire [31:0] \acc0.pp_TRELLIS_FF_Q_DI ;
  /* hdlname = "comp0 B" */
  /* src = "comp.v:2.15-2.16" */
  wire [15:0] \comp0.B ;
  /* hdlname = "control0 clk" */
  /* src = "control_mult.v:3.8-3.11" */
  wire \control0.clk ;
  /* hdlname = "control0 done" */
  /* src = "control_mult.v:9.13-9.17" */
  wire \control0.done ;
  /* hdlname = "control0 init" */
  /* src = "control_mult.v:6.8-6.12" */
  wire \control0.init ;
  /* hdlname = "control0 lsb_B" */
  /* src = "control_mult.v:5.8-5.13" */
  wire \control0.lsb_B ;
  /* force_downto = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] \control0.lsb_B_LUT4_D_1_Z ;
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire \control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_ALUT ;
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire \control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_BLUT ;
  /* force_downto = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] \control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_C0 ;
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire \control0.lsb_B_LUT4_D_Z ;
  /* hdlname = "control0 rst" */
  /* src = "control_mult.v:4.8-4.11" */
  wire \control0.rst ;
  /* hdlname = "control0 state" */
  /* src = "control_mult.v:21.12-21.17" */
  wire [2:0] \control0.state ;
  /* force_downto = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \control0.state_LUT4_B_Z ;
  /* force_downto = 32'd1 */
  /* src = "control_mult.v:56.9-56.9|control_mult.v:35.5-66.11|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" */
  wire [2:0] \control0.state_TRELLIS_FF_Q_DI ;
  wire \control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ;
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ;
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ;
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire init_LUT4_B_Z;
  /* hdlname = "lsr0 clk" */
  /* src = "lsr.v:2.9-2.12" */
  wire \lsr0.clk ;
  /* hdlname = "lsr0 in_A" */
  /* src = "lsr.v:3.15-3.19" */
  wire [15:0] \lsr0.in_A ;
  /* hdlname = "lsr0 s_A" */
  /* src = "lsr.v:6.20-6.23" */
  wire [31:0] \lsr0.s_A ;
  wire [15:1] \lsr0.s_A_TRELLIS_FF_Q_31_DI ;
  /* hdlname = "rsr0 clk" */
  /* src = "rsr.v:2.9-2.12" */
  wire \rsr0.clk ;
  /* hdlname = "rsr0 in_B" */
  /* src = "rsr.v:3.15-3.19" */
  wire [15:0] \rsr0.in_B ;
  /* hdlname = "rsr0 s_B" */
  /* src = "rsr.v:6.20-6.23" */
  wire [15:0] \rsr0.s_B ;
  wire [14:0] \rsr0.s_B_TRELLIS_FF_Q_9_DI ;
  wire \rsr0.s_B_TRELLIS_FF_Q_CE ;
  wire \rsr0.s_B_TRELLIS_FF_Q_LSR ;
  /* src = "mult_32.v:16.15-16.18" */
  wire [31:0] w_A;
  /* src = "mult_32.v:17.15-17.18" */
  wire [15:0] w_B;
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B (
    .A(1'h0),
    .B(A[1]),
    .C(\lsr0.s_A [0]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_1 (
    .A(1'h0),
    .B(A[2]),
    .C(\lsr0.s_A [1]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_10 (
    .A(1'h0),
    .B(A[11]),
    .C(\lsr0.s_A [10]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_11 (
    .A(1'h0),
    .B(A[12]),
    .C(\lsr0.s_A [11]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_12 (
    .A(1'h0),
    .B(A[13]),
    .C(\lsr0.s_A [12]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_13 (
    .A(1'h0),
    .B(A[14]),
    .C(\lsr0.s_A [13]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_14 (
    .A(1'h0),
    .B(A[15]),
    .C(\lsr0.s_A [14]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_2 (
    .A(1'h0),
    .B(A[3]),
    .C(\lsr0.s_A [2]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_3 (
    .A(1'h0),
    .B(A[4]),
    .C(\lsr0.s_A [3]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_4 (
    .A(1'h0),
    .B(A[5]),
    .C(\lsr0.s_A [4]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_5 (
    .A(1'h0),
    .B(A[6]),
    .C(\lsr0.s_A [5]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_6 (
    .A(1'h0),
    .B(A[7]),
    .C(\lsr0.s_A [6]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_7 (
    .A(1'h0),
    .B(A[8]),
    .C(\lsr0.s_A [7]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_8 (
    .A(1'h0),
    .B(A[9]),
    .C(\lsr0.s_A [8]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_9 (
    .A(1'h0),
    .B(A[10]),
    .C(\lsr0.s_A [9]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B (
    .A(1'h0),
    .B(B[0]),
    .C(\rsr0.s_B [1]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_1 (
    .A(1'h0),
    .B(B[1]),
    .C(\rsr0.s_B [2]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_10 (
    .A(1'h0),
    .B(B[10]),
    .C(\rsr0.s_B [11]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_11 (
    .A(1'h0),
    .B(B[11]),
    .C(\rsr0.s_B [12]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_12 (
    .A(1'h0),
    .B(B[12]),
    .C(\rsr0.s_B [13]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_13 (
    .A(1'h0),
    .B(B[13]),
    .C(\rsr0.s_B [14]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_14 (
    .A(1'h0),
    .B(B[14]),
    .C(\rsr0.s_B [15]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_2 (
    .A(1'h0),
    .B(B[2]),
    .C(\rsr0.s_B [3]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_3 (
    .A(1'h0),
    .B(B[3]),
    .C(\rsr0.s_B [4]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_4 (
    .A(1'h0),
    .B(B[4]),
    .C(\rsr0.s_B [5]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_5 (
    .A(1'h0),
    .B(B[5]),
    .C(\rsr0.s_B [6]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_6 (
    .A(1'h0),
    .B(B[6]),
    .C(\rsr0.s_B [7]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_7 (
    .A(1'h0),
    .B(B[7]),
    .C(\rsr0.s_B [8]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_8 (
    .A(1'h0),
    .B(B[8]),
    .C(\rsr0.s_B [9]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_9 (
    .A(1'h0),
    .B(B[9]),
    .C(\rsr0.s_B [10]),
    .D(\control0.state_LUT4_B_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0  (
    .A0(\lsr0.s_A [8]),
    .A1(\lsr0.s_A [9]),
    .B0(\acc0.pp [8]),
    .B1(\acc0.pp [9]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_1_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [8]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_1  (
    .A0(\lsr0.s_A [6]),
    .A1(\lsr0.s_A [7]),
    .B0(\acc0.pp [6]),
    .B1(\acc0.pp [7]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_2_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [6]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_10  (
    .A0(\lsr0.s_A [18]),
    .A1(\lsr0.s_A [19]),
    .B0(\acc0.pp [18]),
    .B1(\acc0.pp [19]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_11_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_10_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [18]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_11  (
    .A0(\lsr0.s_A [16]),
    .A1(\lsr0.s_A [17]),
    .B0(\acc0.pp [16]),
    .B1(\acc0.pp [17]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_12_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_11_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [16]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_12  (
    .A0(\lsr0.s_A [14]),
    .A1(\lsr0.s_A [15]),
    .B0(\acc0.pp [14]),
    .B1(\acc0.pp [15]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_13_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_12_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [14]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_13  (
    .A0(\lsr0.s_A [12]),
    .A1(\lsr0.s_A [13]),
    .B0(\acc0.pp [12]),
    .B1(\acc0.pp [13]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_14_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_13_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [12]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_14  (
    .A0(\lsr0.s_A [10]),
    .A1(\lsr0.s_A [11]),
    .B0(\acc0.pp [10]),
    .B1(\acc0.pp [11]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_14_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [10]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_15  (
    .A0(\lsr0.s_A [0]),
    .A1(\lsr0.s_A [1]),
    .B0(\acc0.pp [0]),
    .B1(\acc0.pp [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\acc0.pp_CCU2C_B0_15_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [0]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_2  (
    .A0(\lsr0.s_A [4]),
    .A1(\lsr0.s_A [5]),
    .B0(\acc0.pp [4]),
    .B1(\acc0.pp [5]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_4_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_2_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [4]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_3  (
    .A0(\lsr0.s_A [30]),
    .A1(\lsr0.s_A [31]),
    .B0(\acc0.pp [30]),
    .B1(\acc0.pp [31]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_5_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_3_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [30]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_4  (
    .A0(\lsr0.s_A [2]),
    .A1(\lsr0.s_A [3]),
    .B0(\acc0.pp [2]),
    .B1(\acc0.pp [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_15_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_4_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [2]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_5  (
    .A0(\lsr0.s_A [28]),
    .A1(\lsr0.s_A [29]),
    .B0(\acc0.pp [28]),
    .B1(\acc0.pp [29]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_6_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_5_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [28]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_6  (
    .A0(\lsr0.s_A [26]),
    .A1(\lsr0.s_A [27]),
    .B0(\acc0.pp [26]),
    .B1(\acc0.pp [27]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_7_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_6_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [26]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_7  (
    .A0(\lsr0.s_A [24]),
    .A1(\lsr0.s_A [25]),
    .B0(\acc0.pp [24]),
    .B1(\acc0.pp [25]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_8_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_7_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [24]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_8  (
    .A0(\lsr0.s_A [22]),
    .A1(\lsr0.s_A [23]),
    .B0(\acc0.pp [22]),
    .B1(\acc0.pp [23]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_9_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_8_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [22]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_B0_9  (
    .A0(\lsr0.s_A [20]),
    .A1(\lsr0.s_A [21]),
    .B0(\acc0.pp [20]),
    .B1(\acc0.pp [21]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_B0_10_COUT ),
    .COUT(\acc0.pp_CCU2C_B0_9_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [20]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [31]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_1  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [30]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_10  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [21]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_11  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [20]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_12  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [19]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_13  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [18]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_14  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [17]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_15  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [16]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_16  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [15]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_17  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [14]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_18  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [13]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_19  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [12]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_2  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [29]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_20  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [11]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_21  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [10]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_22  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [9]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_23  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [8]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_24  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [7]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_25  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [6]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_26  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [5]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_27  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [4]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_28  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [3]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_29  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [2]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_3  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [28]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_30  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [1]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_31  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [0]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_4  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [27]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_5  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [26]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_6  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [25]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_7  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [24]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_8  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [23]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_9  (
    .CE(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [22]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\acc0.pp [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hfcff)
  ) \control0.lsb_B_LUT4_D  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.lsb_B ),
    .Z(\control0.lsb_B_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_1  (
    .A(\rsr0.s_B [3]),
    .B(\rsr0.s_B [2]),
    .C(\rsr0.s_B [1]),
    .D(\control0.lsb_B ),
    .Z(\control0.lsb_B_LUT4_D_1_Z [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf0ff)
  ) \control0.lsb_B_LUT4_D_1_Z_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state_LUT4_B_Z [2]),
    .D(\control0.lsb_B_LUT4_D_1_Z [2]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hffcf)
  ) \control0.lsb_B_LUT4_D_1_Z_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.lsb_B_LUT4_D_1_Z [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_1_Z_LUT4_Z_1  (
    .A(\rsr0.s_B [15]),
    .B(\rsr0.s_B [14]),
    .C(\rsr0.s_B [13]),
    .D(\rsr0.s_B [12]),
    .Z(\control0.lsb_B_LUT4_D_1_Z [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX \control0.lsb_B_LUT4_D_1_Z_PFUMX_Z  (
    .ALUT(\control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_ALUT ),
    .BLUT(\control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_BLUT ),
    .C0(\control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_C0 [4]),
    .Z(\control0.lsb_B_LUT4_D_1_Z [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\rsr0.s_B [7]),
    .B(\rsr0.s_B [6]),
    .C(\rsr0.s_B [5]),
    .D(\rsr0.s_B [4]),
    .Z(\control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_C0_LUT4_Z  (
    .A(\rsr0.s_B [11]),
    .B(\rsr0.s_B [10]),
    .C(\rsr0.s_B [9]),
    .D(\rsr0.s_B [8]),
    .Z(\control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_C0 [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control0.lsb_B_TRELLIS_FF_Q  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [0]),
    .LSR(1'h0),
    .Q(\control0.lsb_B )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccc3)
  ) \control0.state_LUT4_B  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_LUT4_B_Z [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:31.1-68.4|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_DI [2]),
    .LSR(rst),
    .Q(\control0.state [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:31.1-68.4|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_DI [1]),
    .LSR(rst),
    .Q(\control0.state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:31.1-68.4|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_DI [0]),
    .LSR(rst),
    .Q(\control0.state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0fff)
  ) \control0.state_TRELLIS_FF_Q_DI_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state [1]),
    .D(\control0.state_TRELLIS_FF_Q_DI [1]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0800)
  ) \control0.state_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(\control0.lsb_B_LUT4_D_1_Z [0]),
    .B(\control0.lsb_B_LUT4_D_1_Z [1]),
    .C(\control0.lsb_B_LUT4_D_1_Z [2]),
    .D(\control0.lsb_B_LUT4_D_1_Z [4]),
    .Z(\control0.state_TRELLIS_FF_Q_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control0.state_TRELLIS_FF_Q_DI_LUT4_Z_1  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state [2]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ),
    .C0(\control0.lsb_B_LUT4_D_1_Z [4]),
    .Z(\control0.state_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h07ff)
  ) \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.lsb_B_LUT4_D_1_Z [0]),
    .B(\control0.lsb_B_LUT4_D_1_Z [1]),
    .C(\control0.lsb_B_LUT4_D_1_Z [2]),
    .D(\control0.lsb_B_LUT4_D_1_Z [3]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0fff)
  ) \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.lsb_B_LUT4_D_1_Z [2]),
    .D(\control0.lsb_B_LUT4_D_1_Z [3]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h000c)
  ) done_LUT4_Z (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hfff3)
  ) init_LUT4_B (
    .A(1'h0),
    .B(init),
    .C(\control0.state [2]),
    .D(\control0.state [1]),
    .Z(init_LUT4_B_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX init_LUT4_B_Z_PFUMX_BLUT (
    .ALUT(\control0.lsb_B_LUT4_D_Z ),
    .BLUT(init_LUT4_B_Z),
    .C0(\control0.state [0]),
    .Z(\control0.lsb_B_LUT4_D_1_Z [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [30]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_1  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [29]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_10  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [20]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_11  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [19]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_12  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [18]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_13  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [17]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_14  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [16]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_15  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [15]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_16  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A[0]),
    .LSR(\rsr0.s_B_TRELLIS_FF_Q_LSR ),
    .Q(\lsr0.s_A [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_17  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [15]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_18  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [14]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_19  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [13]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_2  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [28]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_20  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [12]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_21  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [11]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_22  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [10]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_23  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [9]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_24  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [8]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_25  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [7]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_26  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [6]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_27  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [5]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_28  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [4]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_29  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [3]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_3  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [27]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_30  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [2]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_31  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [1]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_4  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [26]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_5  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [25]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_6  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [24]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_7  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [23]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_8  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [22]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:86.171-86.230" */
  TRELLIS_FF #(
    .CEMUX("INV"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_9  (
    .CE(\control0.lsb_B_LUT4_D_1_Z [2]),
    .CLK(clk),
    .DI(\lsr0.s_A [21]),
    .LSR(\control0.state_LUT4_B_Z [2]),
    .Q(\lsr0.s_A [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.s_B_TRELLIS_FF_Q  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(B[15]),
    .LSR(\rsr0.s_B_TRELLIS_FF_Q_LSR ),
    .Q(\rsr0.s_B [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_1  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [14]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_10  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [5]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_11  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [4]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_12  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [3]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_13  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [2]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_14  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [1]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_2  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [13]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_3  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [12]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_4  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [11]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_5  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [10]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_6  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [9]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_7  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [8]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_8  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [7]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_9  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [6]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0030)
  ) \rsr0.s_B_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_LSR )
  );
  assign \control0.state_LUT4_B_Z [1:0] = { \rsr0.s_B [1], B[0] };
  assign \control0.lsb_B_LUT4_D_1_Z_PFUMX_Z_C0 [3:0] = { \rsr0.s_B [4], \rsr0.s_B [5], \rsr0.s_B [6], \rsr0.s_B [7] };
  assign \acc0.A  = \lsr0.s_A ;
  assign \acc0.clk  = clk;
  assign \comp0.B  = { \rsr0.s_B [15:1], \control0.lsb_B  };
  assign \control0.clk  = clk;
  assign \control0.done  = done;
  assign \control0.init  = init;
  assign \control0.rst  = rst;
  assign \lsr0.clk  = clk;
  assign \lsr0.in_A  = A;
  assign pp = \acc0.pp ;
  assign \rsr0.clk  = clk;
  assign \rsr0.in_B  = B;
  assign \rsr0.s_B [0] = \control0.lsb_B ;
  assign w_A = \lsr0.s_A ;
  assign w_B = { \rsr0.s_B [15:1], \control0.lsb_B  };
endmodule
